### ISSUE TITLE
Add new language: Polish

### ISSUE THREAD

**Issue by husk007** [trakt-tools/universal-trakt-scrobbler#104]
Hi, I want to help to translate to polish, but I don't see it in crowdin.

**Comment by MrMamen** [comment]
@rafaelgomesxyz Can you add Polish to Crowdin? I don't seem to have the rights to add new translations.

**Comment by rafaelgomesxyz** [comment]
I'm working on a script to make the process of adding a language more automatic, will see if I can finish it by tomorrow so we can test it here.

**Comment by husk007** [comment]
How is going with script?

**Comment by rafaelgomesxyz** [comment]
Some irl stuff got in the way, but I'm almost done.

**Comment by gordongessler** [comment]
Any updates?

**Comment by rafaelgomesxyz** [comment]
Finally finished the script, sorry it took so long.
