### ISSUE TITLE
Sync history added with current date/time instead of watched date/time

### ISSUE THREAD

**Issue by smoothlystable** [trakt-tools/universal-trakt-scrobbler#105]
This is probably because Trakt now uses UTC datetime instead of unix time stamp: https://trakt.docs.apiary.io/#reference/sync/add-to-history/add-items-to-watched-history

> Send a `watched_at` UTC datetime to mark items as watched in the past. This is useful for syncing past watches from a media center.

I did a quick test by sending the same request, but changed `watched_at` to UTC datetime format instead and it worked.

**Comment by MrMamen** [comment]
I belive this is a regression when migrating away from moment on this commit: https://github.com/trakt-tools/universal-trakt-scrobbler/commit/96c248843e2cd99fb8b0a2fd99a47bf107721e19
