### ISSUE TITLE
Unable to get to authorize modal - loading forever

### ISSUE THREAD

**Issue by mariuswg** [trakt-tools/universal-trakt-scrobbler#110]
I have problems getting to the login/auth modal. It is stuck on the loading icon...
The original traktflix extension works, but not this one.

Has anyone experienced the same issue?

These are the steps I have done:

1. Cloned the repo
2. npm install
3. Copied to a new file; config.json
4. Created an API in Trakt
5. Filled in the clientId and clientSecret
6. npm run build
7. unzipped the chrome.zip file
8. Imported the unpacked plugin to Chrome
9. Opened Netflix
10. Clicked on the extension icon
11. Stuck on the loading icon

![image](https://user-images.githubusercontent.com/18408356/146427135-0f5bbe5f-512a-4ec0-9d98-8d2756381182.png)
![image](https://user-images.githubusercontent.com/18408356/146427147-826a2f38-e8f2-46a0-bc66-8fcc27b450e8.png)

**Comment by isleshocky77** [comment]
I made a comment about this here: https://github.com/trakt-tools/universal-trakt-scrobbler/pull/101#issuecomment-991296107
I was able to get it to work by skipping part of that code.

**Comment by mariuswg** [comment]
Thanks a lot! 
I went back to the commit right before the mentioned PR and it works. I will try to append the commits one by one to check at what point it breaks.

**Comment by isleshocky77** [comment]
@mariuswg https://github.com/trakt-tools/universal-trakt-scrobbler/commit/c00a71889ea91e6d8ff07e26b7eeb90419bd4a4d#diff-157d9bdad81d5f369c2d8ebfaa43942873ed98f97586d573e6d01b124d6bfe6b

It's the way it's checking for errors... when you first start it's null so it's not validated.

**Comment by rafaelgomesxyz** [comment]
Thanks for the info, I'll be looking into this soon.

**Comment by husk007** [comment]
> I made a comment about this here: [#101 (comment)](https://github.com/trakt-tools/universal-trakt-scrobbler/pull/101#issuecomment-991296107) I was able to get it to work by skipping part of that code.

Which part of code and in which file You skipped?

**Comment by isleshocky77** [comment]
@husk007 

```diff
diff --git a/src/common/Session.ts b/src/common/Session.ts
index aa68877..c7ce916 100644
--- a/src/common/Session.ts
+++ b/src/common/Session.ts
@@ -21,9 +21,9 @@ class _Session {
                        }
                } catch (err) {
                        this.isLoggedIn = false;
-                       if (Errors.validate(err)) {
+                       // if (Errors.validate(err)) {
                                await EventDispatcher.dispatch('LOGIN_ERROR', null, { error: err });
-                       }
+                       // }
                }
        }
```

**Comment by husk007** [comment]
@isleshocky77 
Still not working... The same problem - stuck on the loading icon.
