### ISSUE TITLE
Exactly how do I install this? 

### ISSUE THREAD

**Issue by Hillgrove** [trakt-tools/universal-trakt-scrobbler#114]
You mention that this is a replacement for Traktflix which you say doesn't work anymore (it does, I use it), but I can't find a way to install it.

You have a "fake" link to the Chrome Web Store but the link only points to github.

**Comment by bnowakow** [comment]
Follow Readme: https://github.com/trakt-tools/universal-trakt-scrobbler#development
After doing `npm run build-dev` follow https://webkul.com/blog/how-to-install-the-unpacked-extension-in-chrome/ with extension folder location in `build/chrome` directory.

**Comment by Hillgrove** [comment]
Ahh.. It's stil in dev it seems. I thought it had been released. My bad. I will be a bit more patient.

**Comment by Manfred73** [comment]
When will there be a first release for this?
