### ISSUE TITLE
BUG: HBO Max not scrobbling + history sync not working - EU

### ISSUE THREAD

**Issue by smoothlystable** [trakt-tools/universal-trakt-scrobbler#116]
HBO Max doesn't seem to work for me at all, neither scrobbling or sync. 

### When trying to sync history
If I have scrobble disabled and sync enabled in settings, a new tab for play.hbomax.com opens up and I just get stuck with the loading circle on the history page:
![image](https://user-images.githubusercontent.com/20187834/148731327-94dd811d-806a-47e1-bd4f-b5f7af23e4bb.png)

If I have scrobble and sync both enabled, a new tab quickly opens up and closes down and I get the error about not being logged in:
![image](https://user-images.githubusercontent.com/20187834/148731183-07ae11d5-8242-46b8-bf83-236702ec2a59.png)

*I'm guessing the reason why I only get error popup when having scrobbling enabled is another bug.*

No error in Developer console and nothing in Developer network tab. when I'm trying to open history sync page. 

### When trying to scrobble
Nothing happens, no error in developer console and extension just shows the default "Watching something!"-window:
![image](https://user-images.githubusercontent.com/20187834/148731579-5dfb745e-7dbb-49d6-a51c-d0fca247cbe2.png)

I would love to give more info to help solve this, just not sure how to collect relevant info?

**Comment by MrMamen** [comment]
I believe this is a bug in Chrome (not Firefox) where all injection scripts to tabs fail. I've been trying to debug and figuring a different way, but I have not succeed. Perhaps @rafaelgomesxyz or any other with experience with injection can help.

**Comment by ITSYV** [comment]
Can't a DOM fallback work? I was trying this, but the site won't seem to load anymore for me (using a vpn for US).

I was trying to use this code: 
`const titleElement = document.querySelector('[role=heading]');
		// aria-label="Euphoria Season 1 Episode 1: Pilot"
		const matches = /(.+) Season (\d+) Episode (\d+): (.+)/.exec(titleElement?.getAttribute('aria-label') ?? '');

		if (matches) {
			[, showTitle, seasonId, episodeId, epiTitle] = matches;
		}

		const title = showTitle ?? titleElement?.getAttribute('aria-label') ?? '';
		const episodeTitle = epiTitle ?? '';`

Rest of the code is the same as the other services

**Comment by LeviSnoot** [comment]
Getting the same error on v1.0.0-beta. It can be replicated on both Firefox and Chrome.


https://user-images.githubusercontent.com/13402525/156748284-ed841ce8-6e01-44ab-9fe3-dc773c8ee588.mp4
