### ISSUE TITLE
Allow other regions on PrimeVideos Sync

### ISSUE THREAD

**Issue by iamjabour** [trakt-tools/universal-trakt-scrobbler#117]
Hi, this is a problem with different regions with Primevideos. Allow user to select from [eu,na,fe] options for api url formation.

easy fix but needs user input, attached the list of dns for for the api to resolve the getitem. in my case i need to change AmazonPrimeAPI.js:124 from `API_URL = 'https://atv-ps.primevideo.com';` to `API_URL = 'https://atv-ps-fe.primevideo.com` 

and works for me in my region, otherwise I get a region error saying my profile is not from the provided region.

Not the exact dns but an guide attached the dns list from here: https://decoder.link/sslchecker/atv-ps-eu.amazon.de/443
![Screen Shot 2022-01-13 at 6 43 19 AM](https://user-images.githubusercontent.com/446037/149196529-a421f12c-4905-4495-af2f-7cc62b4b52ba.png)

**Comment by ITSYV** [comment]
Maybe this can even be automated, the json error outputted when getting the wrong url contains the correct region:
{ "error": "wrong_region", "customer_home_region": "EU" }

**Comment by bnowakow** [comment]
For sb that want's to replicate it's src/services/amazon-prime/AmazonPrimeApi.ts (not AmazonPrimeAPI.js).

I live in Poland, Europe and when querying https://atv-ps-fe.primevideo.com/cdp/catalog/GetPlaybackResources (...) I still get {"error": "wrong_region", "customer_home_region": "EU"}

**Comment by bnowakow** [comment]
Nice. Changing API_URL = 'https://atv-ps-eu.primevideo.com'; has helped in Poland, Europe - thx!

**Comment by eRJeeBuch** [comment]
> Nice. Changing API_URL = 'https://atv-ps-eu.primevideo.com'; has helped in Poland, Europe - thx!

For Prime Video Netherlands this link also work! Great work all, much appriciated!

**Comment by ITSYV** [comment]
Is the correct data retrieved when you change the url to the eu server?
I just tried this, and though it states my profile is selected, it doesn't seem to load my history but instead it seems to retrieve the history of the main user.

@MrMamen @rafaelgomesxyz is this another bug?

**Comment by bnowakow** [comment]
> I just tried this, and though it states my profile is selected, it doesn't seem to load my history but instead it seems to retrieve the history of the main user.

I'm using one profile on prime, maybe because of that I didn't observe this behaviour.

**Comment by MrMamen** [comment]
@rafaelgomesxyz lives outside Europe, perhaps he can debug.

**Comment by profucius** [comment]
I live in NA region. and I did some testing on this on my own #122 . It seems these may or at not be related, as I cannot get the extension to respond to the amazon prime API, even when changing it out to some other options from the OP in this thread.

**Comment by sla-te** [comment]
I live in DE and the only way to partly get it to work is changing HOST_URL to https://www.amazon.de API_URL to https://atv-ps-eu.amazon.de and SETTINGS_URL to ${this.HOST_URL}/gp/video/settings but all the names are on german now and, so it does not find a lot of them on trakt. I also changed homePage and hostPatterns in AmazonPrimeService.ts to amazon.de..

**Comment by rafaelgomesxyz** [comment]
Closing as duplicate of #99.

**Comment by rafaelgomesxyz** [comment]
@iamjabour Can you post what you get when going here: https://atv-ps.primevideo.com/cdp/catalog/GetPlaybackResources?asin=amzn1.dv.gti.1eb29f5a-8c64-d2a4-d3c0-3ea3d4881b14&consumptionType=Streaming&desiredResources=CatalogMetadata&deviceID=893a1a327cc0f9500d366ae5b893590360d1253c0a5cdf83b0253b82&deviceTypeID=AOAGZA014O5RE&firmware=1&gascEnabled=true&resourceUsage=CacheResources&videoMaterialType=Feature&titleDecorationScheme=primary-content&uxLocale=en_US

**Comment by MrMamen** [comment]
When I call this I get:
`{ "error": "wrong_region", "customer_home_region": "EU" }`

**Comment by ITSYV** [comment]
Same error for me here in Belgium

> When I call this I get: `{ "error": "wrong_region", "customer_home_region": "EU" }`

**Comment by rafaelgomesxyz** [comment]
Yeah, I wanted to see what it says for @iamjabour because he says `atv-ps-fe` works for him. I know `atv-ps` works for `NA` and `atv-ps-eu` works for `EU`, so not sure what's the `customer_home_region` that `atv-ps-fe` works for.

**Comment by ITSYV** [comment]
It seems atv-ps-fe also has a .co.jp domain.
Sooo, i just tested with a VPN with "Japan" and got this error: "{ "error": "wrong_region", "customer_home_region": "FE" }" 😉

**Comment by rafaelgomesxyz** [comment]
> It seems atv-ps-fe also has a .co.jp domain. Sooo, i just tested with a VPN with "Japan" and got this error: "{ "error": "wrong_region", "customer_home_region": "FE" }" 😉

Thank you!

**Comment by ITSYV** [comment]
A google result gave me the next info: 
atv-ps: .com
atv-ps-eu: .co.uk and .de
atv-ps-fe: .co.jp

and that's for the "amazon.tld" domain

**Comment by rafaelgomesxyz** [comment]
Yeah, I found something in the script for the Prime page that should help with the domains:

```
n.getDomainFromMarketplaceId = function(e) {
    switch (e) {
        case Y.ROW_NA:
        case Y.ROE_EU:
        case Y.ROW_EU:
        case Y.ROW_FE:
            return ".primevideo.com";
        case Y.DE:
            return ".amazon.de";
        case Y.JP:
            return ".amazon.co.jp";
        case Y.UK:
            return ".amazon.co.uk";
        default:
            return ".amazon.com"
    }
},
n.EU_REGION = "atv-ps-eu",
n.JP_REGION = "atv-ps-fe",
n.US_REGION = "atv-ps",
```

**Comment by profucius** [comment]
> @iamjabour Can you post what you get when going here: https://atv-ps.primevideo.com/cdp/catalog/GetPlaybackResources?asin=amzn1.dv.gti.1eb29f5a-8c64-d2a4-d3c0-3ea3d4881b14&consumptionType=Streaming&desiredResources=CatalogMetadata&deviceID=893a1a327cc0f9500d366ae5b893590360d1253c0a5cdf83b0253b82&deviceTypeID=AOAGZA014O5RE&firmware=1&gascEnabled=true&resourceUsage=CacheResources&videoMaterialType=Feature&titleDecorationScheme=primary-content&uxLocale=en_US

I get this (NA region):

`{"errorsByResource":{"CatalogMetadata":{"errorCode":"PRS.Dependency","message":"Cannot complete request.","type":"PRSDependencyException"}},"returnedTitleRendition":{"asin":"amzn1.dv.gti.1eb29f5a-8c64-d2a4-d3c0-3ea3d4881b14","assetBundleVideoQuality":"HD","audioQuality":"Stereo","contentId":"amzn1.dv.vcid.99f79bd4-d740-46da-bbbf-6a309206383c","selectedEntitlement":{"rightsException":{"errorCode":"PRS.NoRights.NotOwned","message":"Cannot complete request.","type":"PRSOwnershipException"}},"titleId":"amzn1.dv.gti.1eb29f5a-8c64-d2a4-d3c0-3ea3d4881b14","videoMaterialType":"Feature","videoQuality":"HD","videoResolution":"1080p"}}`

**Comment by rafaelgomesxyz** [comment]
@profucius Can you check the network requests in the console while hitting play on something and looking for any requests to `GetPlaybackResources`? Then if you could post the URL that was requested, that would be really helpful.

**Comment by profucius** [comment]
I tried looking for that in my console by using the filter, but found no reference to that while playing a video. Is there something else I can try, some other browser, or any other information?

**Comment by rafaelgomesxyz** [comment]
It has to be before you click the play button on an episode/movie from the homepage. And the network tab has to be open before you do that, otherwise it won't log. If there's still no requests, try filtering by "Fetch/XHR" and seeing if any of the requests are retrieving information about the title.

**Comment by iamjabour** [comment]
> @iamjabour Can you post what you get when going here: https://atv-ps.primevideo.com/cdp/catalog/GetPlaybackResources?asin=amzn1.dv.gti.1eb29f5a-8c64-d2a4-d3c0-3ea3d4881b14&consumptionType=Streaming&desiredResources=CatalogMetadata&deviceID=893a1a327cc0f9500d366ae5b893590360d1253c0a5cdf83b0253b82&deviceTypeID=AOAGZA014O5RE&firmware=1&gascEnabled=true&resourceUsage=CacheResources&videoMaterialType=Feature&titleDecorationScheme=primary-content&uxLocale=en_US

 @rafaelgomesxyz , sorry for delay response. I get this:
{ "error": "wrong_region", "customer_home_region": "FE" }

In in NZ. So maybe the Asia region is FE

**Comment by ArslanAmeer** [comment]
I have updated `API-URL: https://atv-ps.primevideo.com/` to `API-URL: https://atv-ps-eu.primevideo.com/` in amazon-prime.js, history.js, background.js files.
Reloading extension after update fix my issue.

**Comment by profucius** [comment]
I have tried the above solution by ArslanAmeer, and it did not work for me. The same issue persists: 

Load Extension Options > Enable Sync on Amazon prime > Click "go to history page" > Two tabs open > One is amazon prime video settings page, the other is a black background with a spinning wheel in the middle, which continues spinning indefinitely with no other data on the page.

I detailed all of this in #122

**Comment by rafaelgomesxyz** [comment]
I'll try to finally take a look this weekend.

**Comment by ArslanAmeer** [comment]
> I have tried the above solution by ArslanAmeer, and it did not work for me. The same issue persists:
> 
> Load Extension Options > Enable Sync on Amazon prime > Click "go to history page" > Two tabs open > One is amazon prime video settings page, the other is a black background with a spinning wheel in the middle, which continues spinning indefinitely with no other data on the page.
> 
> I detailed all of this in #122

Try removing Extension first, then updating files and reload extension again. Make sure you open Amazon Prime in chrome.

**Comment by profucius** [comment]
> Try removing Extension first, then updating files and reload extension again. Make sure you open Amazon Prime in chrome.

I have done this multiple times, no change. Using chrome already.

**Comment by mwillacey71** [comment]
Is there a way to change the site the extension uses for prime? I'm a NA user but it keeps going to primevideo.com

**Comment by bnowakow** [comment]
> Is there a way to change the site the extension uses for prime? I'm a NA user but it keeps going to primevideo.com

you can change it manually in source https://github.com/trakt-tools/universal-trakt-scrobbler/issues/117#issuecomment-1011950901

**Comment by rafaelgomesxyz** [comment]
Finally made a PR for it: https://github.com/trakt-tools/universal-trakt-scrobbler/pull/160

If some of you from NA/EU/JP could test the `.zip` files I provided in the PR and see if it works for both scrobbling and syncing, I'd appreciate it.

@profucius Your case might need something else, but let me know if this works for you.

**Comment by ITSYV** [comment]
@rafaelgomesxyz Working here in Belgium - Europe 👍 both scrobling & history sync

**Comment by nextux** [comment]
Added Australian Amazon site to list....

https://github.com/trakt-tools/universal-trakt-scrobbler/pull/383
