### ISSUE TITLE
History suddenly doesn't work anymore - no more data from streaming service (movie or series deleted)

### ISSUE THREAD

**Issue by eRJeeBuch** [trakt-tools/universal-trakt-scrobbler#118]
Error: 

https://user-images.githubusercontent.com/66549251/149373189-cc49ff48-af62-44cc-b734-c0022c45e578.jpg

[UTS] Failed to load history. TypeError: Cannot read properties of undefined (reading 'season')

Context
history.html#/netflix
Stack-tracering
history.js:52766 (error)
history.js:48170 (_callee$)
history.js:112146 (tryCatch)
history.js:112377 (invoke)
history.js:112202 (anonieme functie)
history.js:116676 (asyncGeneratorStep)
history.js:116702 (_throw)

Tried building 3 different builds, same results.
Something changed on Netflix side's listing?

**Comment by ITSYV** [comment]
Not sure, but still working in Belgium
Do you get the same result when clearing cache & removing data?
Can you check your recent viewing activity on Netflix (https://www.netflix.com/viewingactivity). Is there something different since you get this error? Maybe a show or movie which doesn't have all the data

**Comment by eRJeeBuch** [comment]
Definitely something with a show or movie. One of the other profile's just load.

So next step is: How can I check if a show or movie doesn't have all the data?

**Comment by eRJeeBuch** [comment]
So I found out that when a serie or movie isn't available anymore on the streaming service (in this particular case Prison Break on Netflix NL), the above error occurs. So I deleted it from the viewing activity and now synchronises.

**Comment by ITSYV** [comment]
Can we reopen this as a bug? @MrMamen

**Comment by rafaelgomesxyz** [comment]
Ooh, I think this explains the bug that was happening where some Netflix items didn't have a `summary` prop: https://github.com/trakt-tools/universal-trakt-scrobbler/pull/136

I had gotten the exact same error as the OP for Friends when I found that bug, and I thought it was an issue with some shows on Netflix, but Friends was also removed from Netflix (at least in Brazil), so it makes sense.

I'm assuming this is fixed and closing it.
