### ISSUE TITLE
Suggestion: move to GitLab

### ISSUE THREAD

**Issue by rafaelgomesxyz** [trakt-tools/universal-trakt-scrobbler#13]
@MrMamen Do you have any problems with moving the project to GitLab? It's not a big deal, just a personal preference, as I'm moving to more open source alternatives that aren't owned by major corporations, since GitHub is closed-source and owned by Microsoft. But if you don't want to, we can keep it here. Like I said, no big deal.

**Comment by MrMamen** [comment]
I don't really mind that Microsoft owns Github nor that it is closed source. I like my profile at GitHub, and I don't see any advantages of switching to GitLab at this time.

**Comment by rafaelgomesxyz** [comment]
No problem.
