### ISSUE TITLE
HBO Max: History item url fails to load, breaking history sync

### ISSUE THREAD

**Issue by smoothlystable** [trakt-tools/universal-trakt-scrobbler#133]
I'm getting "Failed to load history" when trying to sync HBO Max history. 

Status 500 when trying to request one of the endpoints for a movie, the response is:
`{"message":"An unknown problem occurred. Please contact your TV provider.","statusCode":500}`

I looked up what the URL looks like for when browsing the webpage normally, and it seems that what's breaking it is the missing of the following parameters:
```
&brand=HBO%20MAX&territory=NORDICS&navigation-channels=HBO%20MAX%20SUBSCRIPTION%7CHBO%20MAX%20FREE&upsell-channels=HBO%20MAX%20SUBSCRIPTION%7CHBO%20MAX%20FREE&playback-channels=HBO%20MAX%20SUBSCRIPTION%7CHBO%20MAX%20FREE
```

Here's the URL that's failing (adding the above parameters makes it work): https://comet-emea.api.hbo.com/express-content/urn:hbo:feature:GX9KHPw1OIMPCJgEAAAAD?device-code=desktop&product-code=hboMax&api-version=v9.0&country-code=US&language=en-us

**Comment by rafaelgomesxyz** [comment]
Thanks for the info.

Looks like different regions have different params, because in my region it works without the additional params.

**Comment by smoothlystable** [comment]
It's weird though, because it doesn't seem to be consistent. That URL works now, but instead another URL (https://comet-emea.api.hbo.com/express-content/urn:hbo:feature:GXnEEqw6S3A4eoAEAABiR?device-code=desktop&product-code=hboMax&api-version=v9.0&country-code=US&language=en-us) isn't working, adding params still does the trick though. 

So what's consistent is:
* Every time I open the history sync page, at least one of the requests fails with 500
* Failed URL starts working when adding the params

**Comment by netcaretx** [comment]
For me in the US I get the first nine items only. I really wish it was more is that normal?

**Comment by fiveoone** [comment]
Still have issues with HBO Max in The Netherlands. My history doesn't show any items whatsoever and therefore it can't sync either. I'm using Beta (2022-03-27T20:51:11.241Z) from https://github.com/trakt-tools/universal-trakt-scrobbler/releases/tag/beta -- anything I can do to check it? Netflix seem to be working great at the moment!

**Comment by rafaelgomesxyz** [comment]
Please try the `.zip` files from this PR and let me know if it's fixed: https://github.com/trakt-tools/universal-trakt-scrobbler/pull/162

**Comment by fiveoone** [comment]
Hi there, unfortunately, it didn't do the trick for me. I get stuck in a 'loading' screen with no changes. I don't have a huge amount of watched things on HBO Max either so it should be faster (Netflix loads successively almost immediately)
<img width="847" alt="Screenshot 2022-05-23 at 10 39 20" src="https://user-images.githubusercontent.com/65599017/169779668-8881686d-f7ed-4298-8ec8-8fc4429eae1b.png">
.

**Comment by rafaelgomesxyz** [comment]
HBO Max is actually a bit slow because it needs 1 request for each watched item, unlike Netflix, where you get everything in 1 request. Do you know how to open the console for the background page of the extension and go to the Network tab to watch the requests?

**Comment by fiveoone** [comment]
I think I found the Network tab in the console. I'll leave it on for a bit to make sure HBO Max has all the time it needs and to see if anything changes, but this is everything that's happening so far. Please let me know if I can do anything else!

<img width="557" alt="Screenshot 2022-05-23 at 14 15 55" src="https://user-images.githubusercontent.com/65599017/169817304-1f5869a5-84b4-4928-b63a-c430ae52bd4a.png">

Or maybe this is what you're looking for:
<img width="552" alt="Screenshot 2022-05-23 at 14 29 59" src="https://user-images.githubusercontent.com/65599017/169819650-17299d8c-bc48-4432-b6a5-e47f6228a2e6.png">

**Comment by fiveoone** [comment]
Hey, anything else I can do to help you get to the bottom of this? Tried it again now but same issue, just loads and loads and nothing comes up. I absolutely understand if you haven't had the time or other priorities, just wanted to check in.

**Comment by Hillgrove** [comment]
getting same issues

**Comment by rafaelgomesxyz** [comment]
Hey guys, could you try the `.zip` files from https://github.com/trakt-tools/universal-trakt-scrobbler/pull/162 and see if it's fixed for you?

**Comment by Hillgrove** [comment]
> Hey guys, could you try the `.zip` files from #162 and see if it's fixed for you?

that seems to have fixed HBO Max for me.. Is this the same update as the new beta release?

**Comment by rafaelgomesxyz** [comment]
> that seems to have fixed HBO Max for me..

Awesome.

> Is this the same update as the new beta release?

Nope. Beta is only for what's on `master`. #162 hasn't been merged yet, but if more people confirm it's working I'll probably merge it later.

**Comment by Hillgrove** [comment]
aight.. welcome "back" and keep up the good work. Hopefully the new manifest doesn't screw you (us?) over completely.
