### ISSUE TITLE
Syncing history Netflix stuck / crashing

### ISSUE THREAD

**Issue by fiveoone** [trakt-tools/universal-trakt-scrobbler#141]
Syncing my Netflix history to Trakt stuck when reaching a high amount and old items. No matter how long I wait, the screen stays like in the attached screenshot:

<img width="1124" alt="Screenshot 2022-03-15 at 09 03 51" src="https://user-images.githubusercontent.com/65599017/158332771-3bf1a08e-2c49-46a2-be76-0f69fd75f3fe.png">
 
The only solution I found so far is to disable 'hide synced', and carefully scroll all the way to the bottom produces some success in loading new items. However, the plugin seems to crash if too many new ones are loaded in and I have to start this process again.

Running Brave Version 1.36.112 Chromium: 99.0.4844.51 (Official Build) (x86_64)

Please let me know if I can attach anything else to help you identify the bug.

**Comment by MrMamen** [comment]
Can you open devtools on history page before the error occurs (you can do this before you select the Netflix-service to be sure) and see if there are errors messages in the console?

**Comment by rafaelgomesxyz** [comment]
Additionally, you could also enable Rollbar in the options so that we can receive any errors you're getting.

**Comment by fiveoone** [comment]
> Can you open devtools on history page before the error occurs (you can do this before you select the Netflix-service to be sure) and see if there are errors messages in the console?

I think I did it the right way. I enabled 'Inspect' then Console and tried again, Netflix > Hide Synced > Waited for it to hide my synced one, then get a crash and I'm back to choosing Netflix as a service. This is the error output:

[ehlckfimahifadnbecobagimllmbdmde-1647362731573.log](https://github.com/trakt-tools/universal-trakt-scrobbler/files/8255486/ehlckfimahifadnbecobagimllmbdmde-1647362731573.log)

I have now enabled Rollbar in the options as well!

**Comment by rafaelgomesxyz** [comment]
I think this is most likely because of the Netflix bug that was fixed in #136. I've deployed a new beta version, please try it and see if it still happens.

**Comment by fiveoone** [comment]
Awesome, I'm sorry but I have no clue how to get the new beta version to work. I've downloaded the chrome.zip from this: https://github.com/trakt-tools/universal-trakt-scrobbler/releases/tag/beta but I think the zip file is corrupted (doesn't unzip on my Mac)

Am I downloading the correct file?

**Comment by rafaelgomesxyz** [comment]
You're right, looks like it's corrupt. Will see if I can fix it later.

**Comment by fiveoone** [comment]
All good no stress - I will check it tomorrow!

Thanks for all the help, I love the plugin otherwise.. so happy it exists!

**Comment by rafaelgomesxyz** [comment]
Hello, any updates?

**Comment by fiveoone** [comment]
Oh, snap! 
I'm sorry I thought I responded to this. Yes, the update has fixed it for me and Netflix works as expected now! Thank you so much.

**Comment by rafaelgomesxyz** [comment]
Awesome!
