### ISSUE TITLE
Viaplay not working

### ISSUE THREAD

**Issue by bart268** [trakt-tools/universal-trakt-scrobbler#148]
I am glad I found this trakt Scrobbler, awesome work.

I have it running with Netflix and HBO Max, only thing I don't get Viaplay to work. When I try to sync Viaplay I get this error:

===
Not Logged In
Looks like you're not logged in to this service. Please go to the page below and log in before trying to sync.

https://viaplay.com/

===

When I click the link, it opens Viaplay where I am logged in so that looks fine. Maybe it has something to do with the region (I'm from The Netherlands)?
I also enabled Rollbar hopefully this gives some information?

**Comment by MrMamen** [comment]
What is the url to Viaplay in your region?

**Comment by bart268** [comment]
The login page: https://viaplay.com/nl-nl/
After login: https://viaplay.com/

**Comment by MrMamen** [comment]
In my region I can see my watch history on this URL:
https://viaplay.no/watched

In the developer tool I can see that it calls this URL to fetch the data:
https://content.viaplay.no/pcdash-no/watched?nextMediaGuid=20455732&nextTimestamp=1589310939561&profileId=E7CA2512C12

Could you provide me with your URL for watch data?

**Comment by bart268** [comment]
I am not fully into the browser development tools but I think this is it.
https://viaplay.com/watched

https://content.viaplay.com/pcdash-nl/watched?profileId=IZmnbwWapGd9m7EKXgqYniIddQabTW17&language=nl

When I open this last URL I get the watched page in something like json. Looking in that data I can see this URL:
https://content.viaplay.com/pcdash-nl/watched?nextMediaGuid=20717488&nextTimestamp=1646942868233

**Comment by bart268** [comment]
I did build the extension with the changes you made. The redirect goes to https://viaplay.com/nl-nl which let me login, however everytime I click the link to sync viaplay history I get logged out again?
If I don't click the link to sync viaplay I can restart the browser without getting logged out.

**Comment by MrMamen** [comment]
Then I haven't been able to fix the issue. On the extension page in chrome (where you install extenstions) could you click on "background" page to open DevTools, and click on the Network-tab. Then try to sync viaplay. See if any of the requests turns red in DevTools. The two I would expect should be something like this:
https://login.viaplay.no/api/persistentLogin/v1?deviceKey=pcdash-no
https://content.viaplay.no/pcdash-no/watched

Which (if any of these fail)? What are your version of these URLS.

Also if opening this URL in your browser:
https://content.viaplay.com/pcdash-nl/watched
What is the result. Please post it here.

**Comment by bart268** [comment]
When I check de devtools, this URL is requested (no other URL's):
https://login.viaplay.com/api/persistentLogin/v1?deviceKey=pcdash-com

This is on that page:
{"success":false,"type":"InvalidDeviceKeyCountryError","name":"InvalidDeviceKeyCountryError","code":3001,"statusCode":400,"message":"Incorrect country code in device key: com. Extracted from deviceKey: pcdash-com"}

When I manually enter this URL I get logged out of viaplay so that must be why the extension is behaving like this now.
If I change the url from pcdash-com to pcdash-nl it shows my login details and won't log me out of viaplay.

The URL "https://content.viaplay.com/pcdash-nl/watched" shows my history in something like json.

**Comment by MrMamen** [comment]
Ahh. It's supposed to be https://login.viaplay.com/api/persistentLogin/v1?deviceKey=pcdash-nl I guess. I'll see if I can fix that.

**Comment by bart268** [comment]
I did a quick change to set my region but not sure if I need to change more, probably...

this.API_BASE_URL = `${this.HOST_URL}pcdash-${region}/`;
this.AUTH_URL = `https://login.${host}/api/persistentLogin/v1?deviceKey=pcdash-${region}`;
to
this.API_BASE_URL = `${this.HOST_URL}pcdash-nl/`;
this.AUTH_URL = `https://login.${host}/api/persistentLogin/v1?deviceKey=pcdash-nl`;

The developer tools now shows "https://login.viaplay.com/api/persistentLogin/v1?deviceKey=pcdash-nl" which is good but still an error I need to login. This is also the only URL the developer tool shows.

This is what is shown when clicking this URL (edited a bit).
`
{"success":true,"userData":{"firstName":"","lastName":"","username":"mail@example.com","userId":"aaaaaaaaaaaaa","numericUserId":"1234567890","isVmsCustomer":false,"isRCCustomer":false,"isTveBCustomer":false,"hasContracts":true,"needsPackage":false,"accountCountry":"NL","accessToken":"bbbbbbbbbbbbbbbbb.ccccccccccccccccccc.dddddddd_eeeeeeeeeeee_fffffffffff-gggggggg","hasAcceptedTermsAndConditions":true,"hasAcceptedPrivacyPolicies":true,"hasAcceptedCookiePolicies":true,"hasAcceptedNewsletters":false,"userIdSplitIo":"alaksdghfaklsfhlkasjfh"},"_links":{"curies":[{"name":"viaplay","href":"http://docs.viaplay.tv/rel/{rel}","templated":true}],"viaplay:home":{"href":"https://content.viaplay.com/pcdash-nl"},"viaplay:logout":{"href":"https://login.viaplay.com/api/logout/v1?deviceKey=pcdash-nl{&forward}","templated":true},"viaplay:newsletter":{"href":"https://login.viaplay.com/api/newsletter","method":"POST"},"viaplay:profiles":{"href":"https://viaplay.mtg-api.com/user-profiles/users/aaaaaaaaaaaaa/profiles","methods":["GET","POST"]},"viaplay:profiles2":{"href":"https://viaplay.mtg-api.com/user-profiles/users/aaaaaaaaaaaaaaaaaa/profiles{?language}","methods":["GET","POST"],"templated":true},"viaplay:profile":{"href":"https://viaplay.mtg-api.com/user-profiles/users/aaaaaaaaaaaaa/profiles/{profileId}","methods":["GET","PUT","DELETE"],"templated":true},"viaplay:profile2":{"href":"https://viaplay.mtg-api.com/user-profiles/users/aaaaaaaaaaaaaaa/profiles/{profileId}{?language}","methods":["GET","PUT","DELETE"],"templated":true},"viaplay:profileAvatars":{"href":"https://viaplay.mtg-api.com/user-profiles/avatars","method":"GET"},"viaplay:userSettings":{"href":"https://viaplay.mtg-api.com/user-settings/{brand}/{locale}/users/{userId}/profiles/{profileId}","methods":["GET"],"templated":true},"viaplay:activate":{"href":"https://login.viaplay.com/api/device/activate?deviceKey=pcdash-nl{&userCode}","templated":true}},"isPersistentLogin":true,"code":1}
`

**Comment by bart268** [comment]
Ok, got it to work.

This is the change I made, I know, this works only for my region but here stops my programming skills...
this.API_BASE_URL = ${this.HOST_URL}pcdash-${region}/;
this.AUTH_URL = https://login.${host}/api/persistentLogin/v1?deviceKey=pcdash-${region};
to
this.API_BASE_URL = ${this.HOST_URL}pcdash-nl/;
this.AUTH_URL = https://login.${host}/api/persistentLogin/v1?deviceKey=pcdash-nl;

But the issue after this was with my viaplay account, I didn't have a first and last name in my profile and when this is empty the login seems to fail for the extension.

**Comment by MrMamen** [comment]
Can you please retry my branch again? You have to revert your fix and pull my latest changes. The only addition is some debug information. Could you please open dev tools on the history page (before you chose viaplay) It supposed to look like this:
```
host viaplay.com
pathname /nl-nl/
region nl
```

Please post this, as well as the values in viaplayURL.
Edit: also fixed the problem with missing profile name

**Comment by bart268** [comment]
host viaplay.com
pathname /watching
region com

**Comment by MrMamen** [comment]
Is this while scrobling? Or history sync? Could you try both?

**Comment by MrMamen** [comment]
It's strange that you get redirected to /watching

**Comment by bart268** [comment]
Maybe I had some caching issues with the /watched path, what I get right now (when using history sync).

When I am logged in to viaplay in another tab and click Viaplay on the history sync button:
(this means I get logged out immediately when I click the link)
host viaplay.com
pathname /
region com

When I am not logged in to viaplay and click Viaplay on the history sync button:
host viaplay.com
pathname /nl-nl
region nl


When I try scrobling, the dev tools are full with errors. There I get the country code "et"?
https://login.viaplay.com/api/persistentLogin/v1?deviceKey=pcdash-et
This way I get logged out from viaplay as soon as I play a movie/serie. Never noticed this because normally I don't use the browser to stream.

**Comment by bart268** [comment]
I suppose the difference in pathname / region is because of the following.

When I am not logged in to viaplay and open https://viaplay.com I get redirected to https://viaplay.com/nl-nl/ After I hit the login button I get redirected to https://viaplay.com without nl-nl.
When I am logged in to viaplay and go to https://viaplay.com then I am not redirected anymore.

**Comment by MrMamen** [comment]
Hmm. Thanks for the info. Not really sure how to handle that case. I have to find the region in a different way than simply parsing an URL.

**Comment by bart268** [comment]
It might be possible however I don't really know how..

Step 1 when I am not logged in seems fine, this gives the right region.
Step 2 read https://login.viaplay.com/api/persistentLogin/v1?deviceKey=pcdash-nl, this gives "accountCountry":"NL"

But that some brainstorm stuff easier said then done...

Or something like extra settings for viaplay to manually configure your region.

**Comment by MrMamen** [comment]
Not being logged in is really the exception. The url you posted already contains -nl at the end.

**Comment by MrMamen** [comment]
What happens if you visit https://viaplay.com/us-en

**Comment by bart268** [comment]
If I am logged in I get redirected to local content. If I am not logged in I see the US page without a login option.

**Comment by bart268** [comment]
I might have found something...
When I go to https://viaplay.com/requirements I am always redirected to https://viaplay.com/nl-nl/requirements

**Comment by MrMamen** [comment]
Thanks for figuring this out. I believe I have a working region determination now.

**Comment by bart268** [comment]
Did a quick check, got a new error now. Not sure if this is something else but if I have time this evening I will clear all caches etc.

When I check in dev tools, nothing is happening on network side, only got some console output.

history.js:2 Current storage version: v8
history.js:200 host viaplay.com
history.js:2 
        
       [UTS] Failed to load history. TypeError: e.EpisodeItem is not a constructor
    at r.value (history.js:200:237329)
    at history.js:200:236891
    at Array.map (<anonymous>)
    at r.value (history.js:200:236865)
    at r.<anonymous> (history.js:75:69572)
    at u (history.js:2:167489)
    at Generator._invoke (history.js:2:167277)
    at Generator.next (history.js:2:167918)
    at t (history.js:2:271964)
    at s (history.js:2:272167)
value @ history.js:2

**Comment by MrMamen** [comment]
I think you forgot to pull the latest version and/or update. The log-statements should not be there anymore. Also I pulled in some updates from master, with updates on package.json (so you should run `npm install`)

**Comment by bart268** [comment]
You were right I was rushing it, seems to be working now 🙂
There is just one more log rule left, rule#117 - console.log('host', host);

One more thing, region selection with scrobbling is not working. Whenever I watch something I get logged out from viaplay.
Last time I checked it did a lookup to https://login.viaplay.com/api/persistentLogin/v1?deviceKey=pcdash-et which should be https://login.viaplay.com/api/persistentLogin/v1?deviceKey=pcdash-nl.

But I don't really use scrobbling, very happy with the history sync!

**Comment by MrMamen** [comment]
Oh. When scrobling, the url doesn't contain region?

**Comment by bart268** [comment]
I see one URL which causes a viaplay logout
https://login.viaplay.com/api/persistentLogin/v1?deviceKey=pcdash-et
I have also seen a URL which ended with something like -ow or something.

**Comment by MrMamen** [comment]
Right. But what is a typical url when playing an episode or movie?

**Comment by bart268** [comment]
Something like https://viaplay.com/player/default/series/shield-the/season-1/episode-1

This example spams the developer tools with this URL:
https://login.viaplay.com/api/persistentLogin/v1?deviceKey=pcdash-ld


And this example: https://viaplay.com/player/default/series/power/season-5/episode-6
Then this URL is accessed: https://login.viaplay.com/api/persistentLogin/v1?deviceKey=pcdash-on

**Comment by MrMamen** [comment]
Yeah. I assumed nl-nl would be in the url, so the region extraction fails miserably. I'll have to make sure it doesn't break, even if I can't determine the correct region.

**Comment by MrMamen** [comment]
I believe I found a way to detect region also when scrobbling. Could you please test?

**Comment by bart268** [comment]
Doesn't seem to work however the URL changed.
Tested again with - https://viaplay.com/player/default/series/shield-the/season-1/episode-1

This URL is called - https://login.viaplay.com/api/persistentLogin/v1?deviceKey=pcdash-com

**Comment by MrMamen** [comment]
Right. I forgot something important. :-( But once more I believe I have solved the issue. If it doesn't work this time I think scrobling has to be deactivated. It is far less important than history sync in my opinion.

**Comment by bart268** [comment]
Very nice, history sync and scrobble are both working now!

Much appreciated
