### ISSUE TITLE
Typescript types be defined where they belong

### ISSUE THREAD

**Issue by MrMamen** [trakt-tools/universal-trakt-scrobbler#15]
typedefs.d.ts currently holds all types. This should be avoided in the future as it grows longer, can cause merge conflicts, and most of them clearly belong to an specific streaming service. They should instead be defined inline (they can still be exported) or in the same directory as the files accessing them. They should not be global if possible, but rather be imported as needed.

**Comment by rafaelgomesxyz** [comment]
Yeah, in another project of mine I just put them in the file where they belong as exports.

**Comment by rafaelgomesxyz** [comment]
This will be taken care of with #12, because the pre-commit hook can't see `global.d.ts`, so it fails.
