### ISSUE TITLE
History Amazon Prime US Not Working

### ISSUE THREAD

**Issue by netcaretx** [trakt-tools/universal-trakt-scrobbler#151]
When you go to history amazon prime in the US, says you are not logged into:
https://www.primevideo.com/

But that URL gets redirected to:
https://www.amazon.com/Amazon-Video/b/?&node=2858778011&redirectToCMP=1
For Example

This is my URL for watch history:
https://www.amazon.com/gp/video/settings/watch-history/ref=atv_set_watch-history

Sorry meant to label as a bug but didn't figure it out.

**Comment by MrMamen** [comment]
I believe this is duplicate of #117 and #99

**Comment by netcaretx** [comment]
I see this is marked as closed and a duplicate but I have read through all the reported issues/duplicates but I do not see a clear solution for US users. I see EU DE etc. mentioned, but nothing for US users. Can I get a list of specific changes to fix amazon-prime.js to get it to work for USA users, please!!!
