### ISSUE TITLE
Netflix - Not Identifying Season when name is Series

### ISSUE THREAD

**Issue by tmowbrey** [trakt-tools/universal-trakt-scrobbler#153]
Hello,

I noticed that for some collections, the term Series is used instead of Season (See The Midwife - https://www.netflix.com/title/70245163). 

I think this has to do with the Netflix API (https://github.com/trakt-tools/universal-trakt-scrobbler/blob/master/src/services/netflix/NetflixApi.ts) on line 263 (const isCollection = !historyItem.seasonDescriptor.includes('Season');) is referencing a collection only by the static value "Season". I believe this needs to be updated to also include "Series" as part of the descriptor.

**Comment by rafaelgomesxyz** [comment]
I believe I've fixed it.

Please test the `.zip` files provided in the PR and confirm: https://github.com/trakt-tools/universal-trakt-scrobbler/pull/161
