### ISSUE TITLE
Failed to correct item. Error: QUOTA_BYTES_PER_ITEM quota exceeded

### ISSUE THREAD

**Issue by cinnamennen** [trakt-tools/universal-trakt-scrobbler#154]
When trying to correct a sync item from Netflix, this error is getting thrown. I am pretty deep into my Netflix history, so perhaps it's a size issue?

**Comment by rafaelgomesxyz** [comment]
It's the browser sync storage. Corrected items are stored there so that they're synced across devices, but it has a few restrictions, so we'll have to adjust for those.
