### ISSUE TITLE
Viaplay - Wrong profile

### ISSUE THREAD

**Issue by Hillgrove** [trakt-tools/universal-trakt-scrobbler#155]
When trying to scrobble (manually) from Viaplay it selects the wrong profile (the owner). 

I'm logged into my own profile but I can't change it.

If I hover over the: 

"History for Viaplay, profile: <insert name>"

it says:

"... swich profiles in the service page"

Where exactly is this "service page" ?

**Comment by MrMamen** [comment]
I can't find a way to use the API which reveals what user profile is selected, or even list all available profiles. So currently this only works with owner/main user.
