### ISSUE TITLE
Cache bug in history sync

### ISSUE THREAD

**Issue by MrMamen** [trakt-tools/universal-trakt-scrobbler#157]
I've found a rare bug where history sync fails to find an finished item due to cache. The issue is that a cached "progress" value prevents the item from syncing. Since the item is cached the new updated progress value is never read.

**Comment by rafaelgomesxyz** [comment]
I don't think it's a rare bug, the cache is never updated with the latest `watchedAt` and `progress` until it expires (which takes 24 hours).
