### ISSUE TITLE
Error loading manifest.json

### ISSUE THREAD

**Issue by ktpires** [trakt-tools/universal-trakt-scrobbler#158]
When I try to install in chrome Versión 100.0.4896.127 (Build oficial) (x86_64), I am receiving this error:

~/universal-trakt-scrobbler-master
Error
Falta el archivo de manifiesto o no se puede leer
No se ha podido cargar el archivo de manifiesto.

Error
The manifest file is missing or cannot be read.
The manifest file could not be loaded.

I try to unzip from beta and master tags, but I receive same error in both cases.

**Comment by rafaelgomesxyz** [comment]
Are there any more details about the error? It seems to be loading fine for me.

**Comment by EduardoOliveira** [comment]
Same problem here,
Chrome 103.0.5060.114 

Can't load manifest file...

**Comment by Orinks** [comment]
Same here. I downloaded the beta and the extracted folder doesn't even contain a manifest.json file. I verified this by looking in the zip archive itself.

**Comment by Orinks** [comment]
If we download the project with Github Desktop, how can we compile it? Or is it a matter of just unpacking it?

**Comment by Manfred73** [comment]
I downloaded the chrome beta tag and dragged the who folder into the extensions of chrome. It gives a manifest error. Current manifest is version 2.0 but that will be deprecated in the future and needs to become 3.0.
The plugin seems to work partly though: it only works for syncing Netflix after I login to my Netflix account. HBO Max and Amazon Primevideo don't seem to work after logging in.

**Comment by Orinks** [comment]
Sadly I think this project has been abandoned.

**Comment by rafaelgomesxyz** [comment]
> Sadly I think this project has been abandoned.

It has not, but this should no longer happen, as the extension has already been upgraded to manifest v3, and was added to the Chrome store.
