### ISSUE TITLE
Missing required parameter: client_id while authorising to trakt oauth

### ISSUE THREAD

**Issue by bnowakow** [trakt-tools/universal-trakt-scrobbler#167]
Running 7d05243322a36bd4b8ab90fe44fa316df14a37e9 
Removed extension, revoked trakt oauth permission, built extension from scratch, installed new extension. When trying to authorise oauth, after login to trakt, got error "Missing required parameter: client_id".

<img width="1136" alt="Screenshot 2022-06-09 at 11 32 48" src="https://user-images.githubusercontent.com/5650258/172817087-b43e373d-a6c8-4c7a-8c45-42753fa6f995.png">

**Comment by bnowakow** [comment]
Is anyone also having above problem? Is still occurring for me in chrome

**Comment by chaptergy** [comment]
If you are running a custom build, have you [set a client ID and secret via the .env file](https://github.com/trakt-tools/universal-trakt-scrobbler#development)?

**Comment by bnowakow** [comment]
Yes, I'm running custom build. I'm so stupid, that was it - thank you!
