### ISSUE TITLE
Add new language: FINNISH

### ISSUE THREAD

**Issue by olavinto** [trakt-tools/universal-trakt-scrobbler#170]

**Comment by olavinto** [comment]
> Language not found. Please make sure that the name is correct and in English.

"Suomi" (language) is Finnish in English. Something fishy is going on! I should know, since I've soon been speaking and writing it for almost 40 years now...

**Comment by rafaelgomesxyz** [comment]
It's just the brackets. They shouldn't be there.

**Comment by olavinto** [comment]
Damn. Should have figured that one out...
