### ISSUE TITLE
Unable to download Plugin from my browser as the link is showing 404 error

### ISSUE THREAD

**Issue by ghost** [trakt-tools/universal-trakt-scrobbler#176]
Hi team, I recently subscribed to Trakt Scrobbler and wanted to use this extension but whenever I am clicking on downloading the file, it is showing me 404 error

**Comment by wickum** [comment]
same here

**Comment by UseTheFork** [comment]
You can find the zip under releases:
https://github.com/trakt-tools/universal-trakt-scrobbler/releases

hope that helps.
