### ISSUE TITLE
Failed to load Netflix history.

### ISSUE THREAD

**Issue by Bioll** [trakt-tools/universal-trakt-scrobbler#192]
Hi there, 

Thank you for your work. Recently, I got an error while syncing my Netflix history on the Chrome website. Hope you guys could take a look at it.

Thanks a lot.
<img width="702" alt="Screen Shot 2022-09-30 at 11 24 38 AM" src="https://user-images.githubusercontent.com/38152649/193183830-eb745199-81d0-4c19-b9c7-614a8a11add9.png">

**Comment by chrisofspades** [comment]
I'm having the same issue. Just started occurring today.

**Comment by Trigger911** [comment]
Here to say I have the same issue ...

**Comment by rafaelgomesxyz** [comment]
Scrobbling broken too, right?
