### ISSUE TITLE
Chrome and Firefox zips no longer in the beta tag

### ISSUE THREAD

**Issue by biskitstix** [trakt-tools/universal-trakt-scrobbler#201]
The zips for the Chrome and Firefox extensions are no longer listed to download under the beta tag since an update a few days ago. I couldn't seem to find them elsewhere. Apologies if I've missed something or if this issue has already been brought to someone's attention.

**Comment by rafaelgomesxyz** [comment]
They're in the releases: https://github.com/trakt-tools/universal-trakt-scrobbler/releases Under assets.

**Comment by biskitstix** [comment]
> They're in the releases: https://github.com/trakt-tools/universal-trakt-scrobbler/releases Under assets.

Visiting that page, for me at least, only displays the message: 
"There aren’t any releases here
You can create a release to package software, along with release notes and links to binary files, for other people to use. Learn more about releases in [our docs](https://docs.github.com/repositories/releasing-projects-on-github/about-releases)."

**Comment by KHouse75** [comment]
I'm here for the same reason.  There aren't any files under releases.

**Comment by rafaelgomesxyz** [comment]
Oops, it wasn't published. Check now.

**Comment by biskitstix** [comment]
> Oops, it wasn't published. Check now.

It's there now! Thank you so much!

**Comment by rafaelgomesxyz** [comment]
You're welcome!
