### ISSUE TITLE
No Chrome.zip or any manifest file

### ISSUE THREAD

**Issue by Tasty-01** [trakt-tools/universal-trakt-scrobbler#204]
The readme says to unzip chrome.zip but there is no such file in the folder. In fact there is no manifest file at all so this can't be added as an extension to Chrome.

Also this link in the readme is dead: https://github.com/trakt-tools/universal-trakt-scrobbler/releases/tag/1.0.0-beta

**Comment by boris377** [comment]
https://github.com/trakt-tools/universal-trakt-scrobbler/releases/

Go to this page instead. They should def update their main page to just go to the releases page.

**Comment by downey-lv** [comment]
This was fixed in 2aec00b129360a0bbb44fc6aba4f3448cf441b23 @rafaelgomesxyz
