### ISSUE TITLE
FER: Add hotstar and Amazon.in

### ISSUE THREAD

**Issue by kdpuvvadi** [trakt-tools/universal-trakt-scrobbler#208]
[hotstar](https://www.hotstar.com/) essentially Disney+ of India.

**Comment by fikimaul** [comment]
I was work on hotstar.com service. But series not yet work, after all work i will merge to this repo. Maybe wanna test the build. 
[chrome.zip](https://github.com/trakt-tools/universal-trakt-scrobbler/files/9835599/chrome.zip)

**Comment by kdpuvvadi** [comment]
any build for firefox?

**Comment by fikimaul** [comment]
[firefox.zip](https://github.com/trakt-tools/universal-trakt-scrobbler/files/9835703/firefox.zip)
this, but i never test the firefox build

**Comment by fikimaul** [comment]
Hi @kdpuvvadi i've new build and fix the series on hotstar. Visit https://github.com/trakt-tools/universal-trakt-scrobbler/pull/212 to test the build
