### ISSUE TITLE
Crunchyroll sync not working

### ISSUE THREAD

**Issue by Catvari** [trakt-tools/universal-trakt-scrobbler#210]
It's impossible to sync with crunchyroll. 
The extension always ask to login on the service even if it's already done.

![image](https://user-images.githubusercontent.com/55973375/197137040-a72c63fc-7f73-452a-b2a7-e11417bad1fa.png)
![image](https://user-images.githubusercontent.com/55973375/197137191-433dcbd1-9d8a-4130-b53a-59cd684b24fa.png)

**Comment by noah978** [comment]
I believe this is due to the URL change. The new site is no longer using the "beta" subdomain. Its just normal crunchyroll now

**Comment by cobrabr** [comment]
Any news on when #216 will be merged to `master`?

**Comment by ipkpjersi** [comment]
I think this can be closed now? It seems like the MR was merged.
