### ISSUE TITLE
Wrong links on Firefox Addons page

### ISSUE THREAD

**Issue by jerone** [trakt-tools/universal-trakt-scrobbler#225]
Links on Firefox Addons page point to (old) url: https://github.com/tegon/traktflix
While it should probably point to here.

https://addons.mozilla.org/en-US/firefox/addon/traktflix/

![image](https://user-images.githubusercontent.com/55841/207867266-35c6b8f6-4d85-473b-a66e-cd4c8193d151.png)

**Comment by downey-lv** [comment]
Traktflix is the old addon so wouldn't it make sense for it to point to the old URL?
The UTS addon (https://addons.mozilla.org/en-US/firefox/addon/universal-trakt-scrobbler/) points here properly
![image](https://user-images.githubusercontent.com/70920705/210177678-3f247f59-b4a9-430a-825f-5b9971e53344.png)

**Comment by jerone** [comment]
Hmmmm, I must have been confused with the different forks. Thanks.
