### ISSUE TITLE
Cannot login into Trakt via Extension

### ISSUE THREAD

**Issue by shomilsaini** [trakt-tools/universal-trakt-scrobbler#226]
After loading the unpacked extension in Chrome.
Login to Trakt.tv takes me to popup with Trakt login page authorization for traktflix.
After login popup goes away but the extension is not authorized..

Please help!

**Comment by NikolaSivkov** [comment]
same thing here. but on Edge beta

**Comment by Jarsky** [comment]
Trying it out on Chrome. Also receiving the same issue. Click Login, it asks for credentials, it asks for permission for traktflix. 
The box goes away and it stays on "Login with Trakt.TV". 

The log gives the error:
`[UTS] Failed to log in. Error: {"request":{"url":"https://api.trakt.tv/oauth/token","method":"POST","body":{"code":"e7692b27fde1xxxxxxxxxxxxxxxxxxxxxxxxxx","client_id":"7a3a721121xxxxxxxxxxxxxxxxxxxxx","client_secret":"575304ddexxxxxxxxxxxxxxxxxxxxxxxx","redirect_uri":"https://ehlckfimahifadnbecobagimllmbdmde.chromiumapp.org/","grant_type":"authorization_code"}},"status":0,"text":"","isCanceled":false}`

Also when installing the extension, theres also a deprecation error:
`Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.`

**Comment by jerone** [comment]
That's because the API is still down: https://status.trakt.tv/

**Comment by shomilsaini** [comment]
> That's because the API is still down: https://status.trakt.tv/

Thanks, it is working now. The API is up. Closing the issue.

Cheers!
