### ISSUE TITLE
Can't sync Amazon Prime in the UK.

### ISSUE THREAD

**Issue by olliebean** [trakt-tools/universal-trakt-scrobbler#229]
If I try to sync from Amazon Prime, I get a popup saying:

> **Not Logged In**
> Looks like you're not logged in to this service. Please go to the page below and log in before trying to sync.
> https://www.primevideo.com/

If I go to the link provided and log in, it redirects me to the UK site, and if I try to view Amazon Prime history from the extension again, I get the same error message.

I searched for this in the issues here, and all I could find was a closed issue where the only solution given seemed to be to edit the amazon URL in the extension source, which is not a workable solution for an end user.

**Comment by badelie** [comment]
Have you looked at issue #99 and issue #160?

**Comment by olliebean** [comment]
> Have you looked at issue #99 and issue #160?

Just looked - so is the version here fixed, but not the version on addons.mozilla.org, then?

**Comment by olliebean** [comment]
Just to update, I've got this working now. It appears that after logging in at https://www.primevideo.com/, I have to refresh the extension's page before I can successfully view the Amazon Prime history. I've whitelisted that domain now so I shouldn't have to log in again.

**Comment by badelie** [comment]
@olliebean, you can close the issue when you reply again if you don't think there is anything remaining.

**Comment by olliebean** [comment]
Thanks, just checked and it's still working so I'll close the issue.

**Comment by jgadelange** [comment]
I still encounter this message. I'm in the Netherlands. Please let me know if I can supply any more information.

I did look at the console. This is the error:
```
[UTS] Failed to activate amazon-prime API Error: {"instance":"RequestError","data":{"request":{"url":"https://atv-ps.primevideo.com/cdp/usage/GetAppStartupConfig?deviceID=&deviceTypeID=AOAGZA014O5RE&firmware=1&gascEnabled=false&version=1","method":"GET","withHeaders":{},"withRateLimit":{"id":"default","maxRPS":{"*":2}}},"status":-1,"isCanceled":false}}
    at f (history.js:2:261381)```
