### ISSUE TITLE
Netflix: [UTS] Failed to sync history. Error: {"request":{"url":"https://api.trakt.tv/sync/history"...

### ISSUE THREAD

**Issue by VapidLinus** [trakt-tools/universal-trakt-scrobbler#237]
The manual sync used to work fine but has stopped working since Trakt's data loss.

I have tried with different browsers and with different episodes. Same error. I installed the latest version of the extension just now to test this again. Notice how the history for none of the episodes load either - it's just stuck at "
LOADING HISTORY..."

Nothing shows up in the "Network" tab when pressing "Sync". There is no network traffic upon pressing "Sync".

![image](https://user-images.githubusercontent.com/4418470/210177320-ac123dd1-a2ce-4872-b606-4bb304fa4d39.png)

```
[UTS] Failed to sync history. Error: {"request":{"url":"https://api.trakt.tv/sync/history","method":"POST","body":{"episodes":[{"ids":{"trakt":4909434},"watched_at":"2022-12-31T23:41:15.000Z"}],"movies":[]},"cancelKey":"sync","withHeaders":{"trakt-api-key":"[REDACTED]","trakt-api-version":"2","Authorization":"Bearer [REDACTED]"},"withRateLimit":{"id":"trakt-api","maxRPS":{"*":1,"GET":3}}},"status":0,"text":"","isCanceled":false}
    at history.js:2:283393
    at p (history.js:2:265649)
    at Generator.<anonymous> (history.js:2:267004)
    at Generator.throw (history.js:2:266012)
    at e (history.js:2:273845)
    at l (history.js:2:274084)
value @ history.js:2
(anonymous) @ history.js:75
p @ history.js:2
(anonymous) @ history.js:2
(anonymous) @ history.js:2
e @ history.js:2
l @ history.js:2
Promise.then (async)
e @ history.js:2
s @ history.js:2
Promise.then (async)
e @ history.js:2
s @ history.js:2
(anonymous) @ history.js:2
(anonymous) @ history.js:2
(anonymous) @ history.js:75
(anonymous) @ history.js:102
p @ history.js:2
(anonymous) @ history.js:2
(anonymous) @ history.js:2
e @ history.js:2
s @ history.js:2
(anonymous) @ history.js:2
(anonymous) @ history.js:2
(anonymous) @ history.js:102
e @ history.js:102
(anonymous) @ history.js:2
p @ history.js:2
(anonymous) @ history.js:2
(anonymous) @ history.js:2
e @ history.js:2
s @ history.js:2
(anonymous) @ history.js:2
(anonymous) @ history.js:2
(anonymous) @ history.js:2
(anonymous) @ history.js:102
p @ history.js:2
(anonymous) @ history.js:2
(anonymous) @ history.js:2
e @ history.js:2
s @ history.js:2
(anonymous) @ history.js:2
(anonymous) @ history.js:2
(anonymous) @ history.js:102
onClick @ history.js:102
He @ history.js:2
Ye @ history.js:2
(anonymous) @ history.js:2
Or @ history.js:2
Cr @ history.js:2
(anonymous) @ history.js:2
De @ history.js:2
(anonymous) @ history.js:2
Ar @ history.js:2
Jt @ history.js:2
Qt @ history.js:2
t.unstable_runWithPriority @ history.js:2
$o @ history.js:2
Ie @ history.js:2
Kt @ history.js:2
```

**Comment by downey-lv** [comment]
When you installed the new version did you do a clean install (i.e. did you delete the extension before updating) and had to log in to Trakt again?

I tried the same request as you did and the episode was successfully added to my history, so I assume there's something going on with your authentication.

For further troubleshooting:
If you open the inspect view for the background page, you should be able to see what exactly is going on with the request after clicking sync.
![image](https://user-images.githubusercontent.com/70920705/211012026-00cbba54-a035-4350-9d71-53f8179d9620.png)
![image](https://user-images.githubusercontent.com/70920705/211010967-41b91387-bbe6-46d0-a311-a4980c1c6a9f.png)

Could you post data from there? 
- Headers -> General
- Payload
- Response

**Comment by VapidLinus** [comment]
> When you installed the new version did you do a clean install (i.e. did you delete the extension before updating) and had to log in to Trakt again?

No, I don't think it was a clean install. Sometimes the extension just "disappears" without me uninstalling it - so I have to install it again. But when I do install it again after having it "disappear", I am stilled logged in.

I was going to try to do a clean install now by making sure to properly uninstall it first, but now I can't install it again because the "Releases" section appears to be empty :p

https://github.com/trakt-tools/universal-trakt-scrobbler/releases
![image](https://user-images.githubusercontent.com/4418470/211017794-58cb685e-4e4d-4ab5-9f4a-e0411aabdfd1.png)

**Comment by downey-lv** [comment]
> Sometimes the extension just "disappears" without me uninstalling it - so I have to install it again. But when I do install it again after having it "disappear", I am stilled logged in.

Since we're installing via zip, Chrome needs to reload the extension on every startup. I guess sometimes it gives up on the extension, but it still saves the settings when you add it back. Shouldn't be an issue when the extension is properly released to the store.

> I was going to try to do a clean install now by making sure to properly uninstall it first, but now I can't install it again because the "Releases" section appears to be empty :p

A new release has been added, you can try it now
