### ISSUE TITLE
Crowdin PRs

### ISSUE THREAD

**Issue by downey-lv** [trakt-tools/universal-trakt-scrobbler#240]
Hi,
Just finished the Latvian translation on Crowdin and was wondering how the translations can/will be merged?
I didn't see any localization commits since March despite there being a lot of activity on Crowdin since then. 

Do they just need to be approved or could this be the issue?
> Never delete the translations branch after merging PRs from Crowdin, as Crowdin uses it to sync changes.

It seems that the translations branch does not exist.

**Comment by rafaelgomesxyz** [comment]
I just updated them. They first need to be approved on Crowdin by proofreaders (neither me nor @MrMamen did that in a long time), then synced to GitHub, so it's not a fully automatic process.

**Comment by MrMamen** [comment]
I've approved some new translations, but how do I sync them with GitHub @rafaelgomesxyz ?
