### ISSUE TITLE
Amazon Prime Video failing to sync (after several successful syncs)

### ISSUE THREAD

**Issue by cristianoisaac** [trakt-tools/universal-trakt-scrobbler#244]
I'm having a problem syncing Amazon Prime Video History using trakt-tools at Chrome. Here is the report of the problem I'm having. After I click on AMAZON PRIME at History SYNC I'm always receiving an error: "Ocorreu um erro ao carregar o histórico. " and this is the Extension error report (I've masked the api-key for security, if it's needed to resolve the problem please PM me):

[UTS] Failed to sync history. Error: {"request":{"url":"https://api.trakt.tv/sync/history","method":"POST","body":{"episodes":[{"ids":{"trakt":6683794},"watched_at":"2022-12-29T16:38:52.000Z"},{"ids":{"trakt":67622},"watched_at":"2022-12-27T15:53:37.000Z"},{"ids":{"trakt":67621},"watched_at":"2022-12-10T14:00:50.000Z"},{"ids":{"trakt":67620},"watched_at":"2022-12-10T13:39:57.000Z"},{"ids":{"trakt":67619},"watched_at":"2022-12-09T00:58:13.000Z"},{"ids":{"trakt":67618},"watched_at":"2022-12-09T00:37:06.000Z"},{"ids":{"trakt":67617},"watched_at":"2022-12-06T03:46:20.000Z"},{"ids":{"trakt":67616},"watched_at":"2022-11-30T23:24:32.000Z"},{"ids":{"trakt":67615},"watched_at":"2022-11-30T23:03:28.000Z"},{"ids":{"trakt":67614},"watched_at":"2022-11-27T22:38:09.000Z"}],"movies":[]},"cancelKey":"sync","withHeaders":{"trakt-api-key":"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX","trakt-api-version":"2","Authorization":"Bearer XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"},"withRateLimit":{"id":"trakt-api","maxRPS":{"*":1,"GET":3}}},"status":0,"text":"","isCanceled":false}
Contexto
history.html#/amazon-prime
Rastreamento de pilha
history.js:2 (value)
history.js:75 (função anônima)
history.js:2 (p)
history.js:2 (função anônima)
history.js:2 (função anônima)
history.js:2 (e)
history.js:2 (l)

Another error in CONSOLE INSPECT at Chrome (F12)

[UTS] Failed to load history. Error: {"request":{"url":"https://www.primevideo.com/gp/video/api/getWatchHistorySettingsPage?widgetArgs=%7B%7D","method":"GET","withHeaders":{"x-requested-with":"XMLHttpRequest"},"withRateLimit":{"id":"default","maxRPS":{"*":2}}},"status":0,"text":"","isCanceled":false}
    at history.js:2:283393
    at p (history.js:2:265649)
    at Generator.<anonymous> (history.js:2:267004)
    at Generator.throw (history.js:2:266012)
    at e (history.js:2:273845)
    at l (history.js:2:274084)
value @ history.js:2

I had already synchronized a lot of episodes from Amazon Prime, but after the first 30+ syncs this error is now permanent when I  try to open the history of Prime.

Also, congrats for this extension, it is really good and hope it keeps getting better!

**Comment by downey-lv** [comment]
Probably related to #211

**Comment by rafaelgomesxyz** [comment]
Closing in favor of https://github.com/trakt-tools/universal-trakt-scrobbler/issues/295.
