### ISSUE TITLE
Unable to sync Amazon Prime Video

### ISSUE THREAD

**Issue by Enterpr1se** [trakt-tools/universal-trakt-scrobbler#279]
### Expected Behavior

Load the sync menu and let user choose which to sync

### Current Behavior

After the first time successfully synchronize.
I cannot synchronize again.
It show fail to load history.

### Steps to Reproduce

1. Open the extension menu
2. Click go to History button
3. It load about 2-3 second and It display fail to load history in the bottom left conner, 
4. It return to "Select a streaming service to sync from:" page

### Additional Information

- **Windows 11 + 22H2:**
- **Chrome + 109.0.5414.122:**
- **Hong Kong/Hong Kong:**

**Comment by gits68** [comment]
hi, same here

**Additional Information**

- Windows 10 22H2
- Firefox 110.0
- France/Paris

**Firefox Console Output**

`[UTS] Failed to load history. Error: {
  "instance": "RequestError",
  "data": {
    "request": {
      "url": "https://www.primevideo.com/gp/video/api/getWatchHistorySettingsPage?widgetArgs=%7B%7D",
      "method": "GET",
      "withHeaders": {
        "x-requested-with": "XMLHttpRequest"
      },
      "withRateLimit": {
        "id": "default",
        "maxRPS": {
          "*": 2
        }
      }
    },
    "status": 403,
    "text": "<!DOCTYPE html>\n<html lang=\"en\" crossorigin=\"anonymous\">\n<head>\n  <title dir=\"ltr\">Page introuvable</title>\n  <meta content=\"IE=Edge,chrome=1\" http-equiv=\"X-UA-Compatible\"><meta content=\"width=device-width, initial-scale=1, maximum-scale=5, user-scalable=0\" name=\"viewport\">\n  <link rel=\"stylesheet\" type=\"text/css\" href=\"https://m.media-amazon.com/images/I/61UJXbdrnFL.css?nav\"><link rel=\"stylesheet\" type=\"text/css\" href=\"https://m.media-amazon.com/images/I/11Zt0+RNsJL.css?footer\">\n  <style>h2{font-weight:400;font-size:17px;line-height:24px}.av-space-large{margin-bottom:24px}.av-space-medium{margin-bottom:16px}.av-button--default{color:#fff;background-color:#3a3a3a}.av-error-container{color:#fff;display:-webkit-box;display:-moz-box;display:-ms-flexbox;display:-webkit-flex;display:flex;height:600px;-webkit-align-items:center;-moz-align-items:center;-ms-align-items:center;align-items:center;justify-content:center;text-align:center}.av-button,a:visited{touch-action:manipulation;padding:14px 20px;border:none;vertical-align:top;-webkit-border-radius:2px;border-radius:2px;-webkit-transition:all .2s ease-out;-o-transition:all .2s ease-out;transition:all .2s ease-out;text-decoration:none}</style>\n</head>\n<body>\n  <header id=\"pv-nav\" class=\"DVWebNode-nav-wrapper DVWebNode pv-nav av-blur-backdrop\"> <div class=\"pv-nav-container pv-nav-cerberus \"> <a href=\"/storefront/home/ref=atv_nb_logo\" class=\"pv-nav-logo\" id=\"pv-nav-logo\"> <div class=\"pv-brand-logo\">Accéder à la page d'accueil</div></a> <div class=\"pv-nav-primary-components\"> <div id=\"pv-nav-main-menu\" class=\"pv-nav-main-menu pv-nav-main-menu-elcano\"> <input type=\"checkbox\" autocomplete=\"off\" id=\"pv-nav-main-menu-trigger\" class=\"pv-nav-main-menu-switch avu-screen-reader-only\"> <label for=\"pv-nav-main-menu-trigger\" class=\"pv-nav-main-menu-label\">Parcourir</label> <ul role=\"navigation\"> <li> <a href=\"/storefront/home/ref=atv_nb_sf_hm\" id=\"pv-nav-home\" class=\"_1NNx6V\">Accueil</a> </li><li> <a href=\"/storefront/ref=nav_shopall_aiv_vid?merchId=RentBuy&amp;ie=UTF8\" id=\"pv-nav-store\" class=\"_1NNx6V\">Boutique</a> </li><li> <a href=\"/storefront/channels/ref=atv_nb_sf_ch\" id=\"pv-nav-channels\" class=\"_1NNx6V\">Chaînes</a></li><li class=\"pv-nav-main-menu-subdropdown\"> <input type=\"checkbox\" autocomplete=\"off\" name=\"pv-nav-main-menu-subdropdown\" id=\"pv-nav-main-menu-subdropdown-trigger-2\"> <label for=\"pv-nav-main-menu-subdropdown-trigger-2\" class=\"pv-nav-main-menu-subdropdown-label\"> <a class=\"\"> <span class=\"pv-nav-main-menu-subdropdown-text\">Catégories</span> </a> </label> <ul class=\"pv-nav-main-menu-subdropdown-flyout\"> <li class=\"subitem\"> <a href=\"/storefront/tv/ref=atv_tc_tv\">Séries</a> </li><li class=\"subitem\"> <a href=\"/storefront/movie/ref=atv_tc_m\">Films</a> </li><li class=\"subitem\"> <a href=\"/storefront/kids/ref=atv_tc_kids\">Enfants</a> </li><li class=\"subitem\"> <a href=\"/storefront/ref=atv_tc_prime?filterId=OFFER_FILTER%3DPRIME\">Inclus avec Amazon Prime</a> </li></ul> </li><li> <a href=\"/mystuff/ref=atv_nb_mystuff\" id=\"pv-nav-mystuff\" class=\"_1NNx6V\">Mon espace</a> </li></ul> </div></div></div></header>\n  <section>\n    <div class=\"av-container av-error-container\">\n      <div>\n        <h2 class=\"av-space-medium\" id=\"error-title\">Page introuvable</h2>\n        <p class=\"av-space-large\" id=\"error-message\">Aucun contenu à l'adresse saisie. Découvrez de nombreux programmes à regarder à la place.</p>\n        <a class=\"av-button av-button--default\" id=\"error-home-link\" href=\"/gp/video/storefront/ref=atv_error_404\">Accéder à la page d'accueil Prime Video</a>\n      </div>\n    </div>\n  </section>\n  <footer id=\"pv-footer\" class=\"DVWebNode-footer-wrapper DVWebNode pv-footer\"> <div class=\"pv-brand-logo\"></div><ul> <li> <a href=\"/ww-av-legal-home/ref=atv_ftr_ter\" class=\"_1NNx6V\">Conditions d'utilisation et Politique de confidentialité</a> </li><li> <a href=\"/contactus/ref=atv_ftr_cu\" class=\"_1NNx6V\">Donnez-nous votre avis</a> </li><li> <a href=\"/help/ref=atv_ftr_hp\" class=\"_1NNx6V\">Aide</a> </li><li>© 1996-{currentYear}, Amazon.com, Inc. ou ses filiales</li></ul> </footer>\n  <script>var f=document.getElementById('pv-footer'); if(f){f.innerHTML=f.innerHTML.replace('{currentYear}',new Date().getFullYear());}</script>\n</body>\n</html>\n\n",
    "isCanceled": false
  }
}`

​

**Comment by gits68** [comment]
hi, it works after you visit the following amazon url : [watch-history](https://www.primevideo.com/region/eu/settings/watch-history/ref=atv_set_watch-history)

**Comment by rafaelgomesxyz** [comment]
Closing in favor of https://github.com/trakt-tools/universal-trakt-scrobbler/issues/295.
