### ISSUE TITLE
It's not working! oAuth fail

### ISSUE THREAD

**Issue by hrqmonteiro** [trakt-tools/universal-trakt-scrobbler#296]
### Expected Behavior

Not to happen and properly login?

### Current Behavior

![Screenshot 2023-04-03 at 12 25 42 PM](https://user-images.githubusercontent.com/17055027/229555919-63ed30b9-3e5a-47c3-ad92-a172e399ee38.png)

### Steps to Reproduce

Just trying to login

### Additional Information

- **OS + Version:** macOS Ventura
- **Browser + Version:** Firefox or Chrome
- **Country/Region:** Brazil

**Comment by MrMamen** [comment]
Is this the zip-file-version, or did you compile the sources yourself?

**Comment by hrqmonteiro** [comment]
> Is this the zip-file-version, or did you compile the sources yourself?

Zip version, and on Firefox i installed through the store

**Comment by rafaelgomesxyz** [comment]
Closing as duplicate of #293
