### ISSUE TITLE
Amazon Prime failed to load history

### ISSUE THREAD

**Issue by hrqmonteiro** [trakt-tools/universal-trakt-scrobbler#298]
### Expected Behavior

To load correctly?

### Current Behavior

At this point i am almost giving up using this extension, basically nothing works. Now is this on Prime:

https://user-images.githubusercontent.com/17055027/230733976-623b5a47-1cb5-4810-a06d-1aa3a921c867.mov

### Steps to Reproduce

Just tried to load history on Prime Video.

### Additional Information

- **OS + Version:** macOS ventura
- **Browser + Version:** Firefox or Chrome, in both this happens
- **Country/Region:** Brazil

**Comment by faethon** [comment]
Same for me, and looking at the issue list this seems to be a bug.

**Comment by lordvault** [comment]
I had the same issue, but works for me following this steps:
1. [https://www.primevideo.com/settings](https://www.primevideo.com/settings) login and be sure to mark the remember me checkbox.
  If you clic the watch history tab you should be able to see your history: 
  
![image](https://user-images.githubusercontent.com/6520372/236061038-2e177ea8-773c-4e91-a336-fc9790f74bef.png)

2. Go to the trakt-scrobbler extension and try again the sync. 

![image](https://user-images.githubusercontent.com/6520372/236061181-ab86254b-ca7d-42fc-b976-15694a7357a8.png)

I hope this works for you. 

Country/Region: Colombia
OS + Version: SteamOS / KDE desktop.
Country/Region: Colombia.

**Comment by rafaelgomesxyz** [comment]
Let's please keep all Amazon Prime problems in a single issue. Closing in favor of https://github.com/trakt-tools/universal-trakt-scrobbler/issues/295 since there are more replies there.

**Comment by jdrx99** [comment]
I don't know why but opening the watched history page and then loading the plugin worked.
