### ISSUE TITLE
Server not found when trying to login with Trakt

### ISSUE THREAD

**Issue by hrqmonteiro** [trakt-tools/universal-trakt-scrobbler#302]
### Expected Behavior

To properly login

### Current Behavior

When i click to login with track, the opened page doesn't work and the extension never logins.

### Steps to Reproduce

[Screencast from 2023-04-12 19-30-41.webm](https://user-images.githubusercontent.com/17055027/231600450-0441f6d6-1166-480b-8c09-5734f6d9622e.webm)

### Additional Information

- **OS + Version:** Fedora 37
- **Browser + Version:** Firefox
- **Country/Region:** Brazil

**Comment by rafaelgomesxyz** [comment]
Do you have the option to grant cookies enabled?
