### ISSUE TITLE
Netflix history not loading

### ISSUE THREAD

**Issue by TimoMeijer** [trakt-tools/universal-trakt-scrobbler#313]
### Expected Behavior

When clicking "History" and selecting "Netflix", it should open the "History" window, to show history & sync information.

### Current Behavior

After clicking "Netflix", the loading icon appears, but stays in the loading state, and a new tab opens with "ERR_FILE_NOT_FOUND"

### Steps to Reproduce

https://github.com/trakt-tools/universal-trakt-scrobbler/assets/1517813/02de52e3-2ea5-44bd-8098-e998fd6916ed

### Additional Information

- Windows 11 22H2 22621.1702
- Chrome 113.0.5672.129
- Netherlands

**Comment by rafaelgomesxyz** [comment]
I just released v0.3.0, which should fix it.

**Comment by TimoMeijer** [comment]
Confirmed fixed, thanks!
