### ISSUE TITLE
Wrapped when logged in

### ISSUE THREAD

**Issue by MrMamen** [trakt-tools/universal-trakt-scrobbler#34]
Possible just on Norwegian localization, but the top bar is wrapped when being logged in:
![loggedout](https://user-images.githubusercontent.com/5688606/92413921-7a519280-f152-11ea-8f20-fffca8b6918a.png)
![loggedin](https://user-images.githubusercontent.com/5688606/92413935-82113700-f152-11ea-83b1-b45b45221235.png)

**Comment by rafaelgomesxyz** [comment]
What do you think about using icons there instead of the names? Because then the size would be the same regardless of language.

**Comment by MrMamen** [comment]
A good idea, as we could and should keep tooltips for explaining what the icons really do.
