### ISSUE TITLE
AmazonPrime: Failed to load history

### ISSUE THREAD

**Issue by lukas-mertens** [trakt-tools/universal-trakt-scrobbler#349]
### Expected Behavior

 - history should be loaded

### Current Behavior

 - Error "Failed to load history"

### Steps to Reproduce

Click on "Amazon Prime":
![CleanShot 2023-11-12 at 23 59 33](https://github.com/trakt-tools/universal-trakt-scrobbler/assets/10901304/1c99dca9-399e-44a8-89b3-38f07c35998c)

I am using the german amazon prime video

### Additional Information

- **OS + Version:** MacOS Sonoma 14.1.1
- **Browser + Version:** Arc Browser (latest)
- **Country/Region:** Germany

**Comment by iMonZ** [comment]
Same issue here using Edge

**Comment by markkhk** [comment]
Me as well in Edge.  Worked on Chrome.

**Comment by ccharlot** [comment]
Same issue here using Brave, MacOs Sonoma and country is France

Edit : managed to make it work after changing language to English

**Comment by jvthomas90** [comment]
Same here on Chrome, MacOS Sonoma

@ccharlot do you mean the browser language? My preferences were set to 

1. English (United States)
2. English

- I deleted "English" first. Still didn't work.
- Then added it back and moved it to the top of that two item list, making it the default. Didn't work either
- Then I deleted "English (United States)" and tried UTS again.

For each variation I first tried logging into Prive Video. When that failed I refreshed the page and tried again. When that too failed I would log out the UTS extension altogether, log back into my Trakt.TV account again, then tried to connect Prime Video history sync one last time. Only when this failed too would I go back to Chrome's browser settings o try another "English" language setting to start this whole process again.

But all 4 combos (3 attempts each) still didn't work, so now I'm wondering whether you meant the language preferences in-browser or if you were referring to another options pae in the OS or something.

Anyway, yeah I've had this problem for a while. I remember not being able to get this extension working when I first installed it on Ventura a while back. Didn't uninstall it though, I figured a bugfix would come someday. Just tried to get it working again today and still no dice. So I thought I'd cast my vote in this issue as well

**Comment by ccharlot** [comment]
> Same here on Chrome, MacOS Sonoma
> 
> @ccharlot do you mean the browser language? My preferences were set to
> 

No, I changed the language on the Prime vidéo website (Account & Settings / Language)

**Comment by markkhk** [comment]
I think this seems to be more related to how Primevideo logon behaves  If I go to Prime seems logged on, but if I try to sync it fails.  If I go to my account page prime requests you to login again (I have two factor on my Amazon account).  Once I log back in the sync works.

**Comment by bnowakow** [comment]
Had same error. Per @markkhk suggestion I've logged out, trakt sync, asked me to sign, signed in, trakt sync and for some reason it started to working ~.~

**Comment by macx** [comment]
I could agree. Logging out from Amazon and login through trakt extension on Amazon works pretty fine. Now I can sync. But correcting any wrong results is not possible.

**Comment by lukas-mertens** [comment]
Signing out and back in again worked for me as well
