### ISSUE TITLE
NRK history sync stopped working

### ISSUE THREAD

**Issue by MrMamen** [trakt-tools/universal-trakt-scrobbler#36]
This seems to be because of an API redesign by NRK.

**Comment by MrMamen** [comment]
This is a bit harder than I initially thought. The new API has:

> access-control-allow-origin: https://tv.nrk.no

@rafaelgssa Do you know if it is even possible to bypass this with JavaScript?

**Comment by MrMamen** [comment]
Possible if I get the execute/injection scripts to work?

**Comment by rafaelgomesxyz** [comment]
Sorry, I'm a bit out of time, will try to look into this tomorrow.

**Comment by MrMamen** [comment]
Not sure if there is anything you could do. I have mapped out the API, but I haven't committed anything. I could do that, but I believe the only way to bypass CORS is a proxy. (Which is bad for privacy) Or possible to open a tab for tv.nrk.no and executing custom code.

**Comment by rafaelgomesxyz** [comment]
Are you positive there's no way to bypass CORS with the extension? Because as far as I know, you can make any requests from the background of an extension, as long as the host is listed in the permissions. What's the host of the new API?

**Comment by MrMamen** [comment]
It seems I forgot to include the correct hostpattern initially. They even have an documentation of their API:
https://psapi-we.nrk.no/documentation/redoc/personlig/
