### ISSUE TITLE
HBO MAX doesn't work anymore since it changed to only MAX

### ISSUE THREAD

**Issue by hrqmonteiro** [trakt-tools/universal-trakt-scrobbler#377]
![image](https://github.com/trakt-tools/universal-trakt-scrobbler/assets/17055027/5a7f7bbb-aaf0-401a-a311-98e87ca68b94)

When will this get fixed?

**Comment by MrMamen** [comment]
I can't seem to find any URLs where history are loaded from.

**Comment by MrMamen** [comment]
Duplicate of: #310
