### ISSUE TITLE
Netflix Error: Failed to load history

### ISSUE THREAD

**Issue by AcidSlide** [trakt-tools/universal-trakt-scrobbler#402]
### Expected Behavior

Should be able to load and sync Netflix Watch History.

### Current Behavior

Upon clicking "Netflix" on the "Select a streaming service to sync from:", an error message pops up having the message "**Failed to load history**"

![image](https://github.com/user-attachments/assets/95a56386-d68e-4baa-837d-60935fe69ea7)

### Steps to Reproduce

1. Open the "Universal Trakt Scrobbler" extension
2. Click on "Netflix" from the list of streaming service
3. Wait for 1-2 secs for the pop error

### Additional Information

Note: I've double checked and the browser is logged in into my Netflix account.

I've traced the error through the developer tool and this was what it showed...
![image](https://github.com/user-attachments/assets/a2d92ad0-ae27-45a2-ba80-b91837e8c773)

```
[UTS] Failed to load history. Error: {"request":{"url":"https://www.netflix.com/api/shakti/mre/viewingactivity?languages=en-US&authURL=1727873878025.YUtFHxmxLQnDfSnfKLUhlGL8muc\\x3D&pg=0","method":"GET","cancelKey":"default","withHeaders":{},"signal":{}},"status":-1,"isCanceled":false}
```

I tried the URL (of course url un-encoded string), and it seems the authURL or key is not valid as Netflix is showing a word "BLOCKED" if the URL is browsed.
![image](https://github.com/user-attachments/assets/38a1e1fa-5c7f-4b77-a30a-566ca6b65f74)

- **Ubuntu (Desktop) 22.04.5 LTS:**
- **Firefox - 130.0.1 (via Snap)**
- **Country/Region:** US/Philippines

**Comment by eugeniosaintemarie** [comment]
I solved it by deleting and re-adding the modified extension saved locally.
The modification of why I have a local version was because of the problem in the login [issues 394](https://github.com/trakt-tools/universal-trakt-scrobbler/issues/394)
![image](https://github.com/user-attachments/assets/9c4467c0-252a-4f75-b612-9675f30dcee7)

**Comment by AcidSlide** [comment]
> I solved it by deleting and re-adding the modified extension saved locally.

Thanks.. that did fix it.  It's the only thing I didn't try was deleting/removing the extension hahaha
