### ISSUE TITLE
Plugin unavailable (404) for download

### ISSUE THREAD

**Issue by Manfred73** [trakt-tools/universal-trakt-scrobbler#53]
The links to the plugin (chrome or firefox) result in a 404. Where can it be downloaded?

**Comment by rafaelgomesxyz** [comment]
This extension is not released yet. For now, you can use [traktflix](https://github.com/tegon/traktflix).

**Comment by Manfred73** [comment]
When do you expect this to be available/released as a plugin for Chrome?

**Comment by rafaelgomesxyz** [comment]
I'm trying to get a release by the end of February, but no promises.
