### ISSUE TITLE
Various problems when scrobbling item not found

### ISSUE THREAD

**Issue by MrMamen** [trakt-tools/universal-trakt-scrobbler#60]
If an item is not found on trakt while scrobling. The PopupWatching-component will still show, but it will show the previous matched show. Also when stoping and/or navigating elsewhere the same component is shown. The easiest way to simulate this is to remove TraktSearch.find here: https://github.com/trakt-tools/universal-trakt-scrobbler/blob/e46d9e97d387a8131ed12ea65fc0970cd4c7e868/src/streaming-services/common/ScrobbleController.ts#L45
and replace it with a throw-statement.

**Comment by rafaelgomesxyz** [comment]
Did #74 fix this?

With 0e8627c, it now properly throws an error when no item was found.

**Comment by MrMamen** [comment]
Yes!
