### ISSUE TITLE
Telia Play needs updating 

### ISSUE THREAD

**Issue by schteff** [trakt-tools/universal-trakt-scrobbler#64]
Telia has completely revamped their Telia Play interface and now use different API endpoints. They now use GraphQL. 

They still have their old interface https://classic.teliaplay.se/ but that might be shut down any time soon. 

The problem with the new interface is that they don't seem to have any timestamp for when a movie/episode was watched or started. They only have the progress minutes and percentage watched. 

The new interface seems to be under constant development (i see multi user management and such features being added every week) so I hope they will add timestamps for media in the future. Until then history sync is not possible.

**Comment by rafaelgomesxyz** [comment]
It's not a problem. HBO Go doesn't have timestamps either. In that
scenario, the user will be asked to manually add a timestamp, or they can
enable the option to use the release date.

**Comment by schteff** [comment]
Aha. Thanks for the info. But since they make changes to the GraphQL structure every week right now I will wait a couple of months before I dive into it to let them stabilize it. And hopefully they will have a timestamp by then. Or maybe even a "watch history" view ready to go, who knows :)

**Comment by rafaelgomesxyz** [comment]
Yeah, no problem.

**Comment by MrMamen** [comment]
@schteff Would it not be better to migrate the URLs to classic until the other one is ready, or that is closed for good? That way it could work for the time being?

**Comment by schteff** [comment]
Yeah, I have actually already done that for myself, though they have added some limitations for the number of episode status calls and changed the way movies are handled. So I have an ugly looking solution which only works for episodes. And then there is the uncertainty of when the old service will be shut down completely.

I'll see if i find the time for refactoring the code and make a new pull request before it is shut down.

**Comment by schteff** [comment]
Now Telia has shut down the classic.teliaplay.se service, so I will try to update the code to use their new API. Unfortunately they have not added any watched timestamp to their data, so that information will be missing as described above. (like HBO). 

I might have time to work on it during the holidays.

**Comment by schteff** [comment]
I have implemented the new Telia Play API connection. But when testing the history sync it seems like the Trakt connection is wonky. 

All items on the trakt side are marked as "Not watched" when "Add with release date" is checked even though they are watched (at the Trakt website), and when signing out and in to Trakt again i see an "OAUTH ERROR"-message after login. 
When "Add with release date" is unchecked all items on the trakt side have the status "LOADING HISTORY...".

When i'm on the latest commit, after having fixes this issue locally https://github.com/trakt-tools/universal-trakt-scrobbler/issues/110 , then the above problems occur. And also when i'm on the "Add sync for Amazon Prime (#98)" commit the same problems occur.

**Comment by rafaelgomesxyz** [comment]
Will take a look this week.

**Comment by schteff** [comment]
Nice fixing #110 , but that was unrelated.

I still cannot fetch the trakt status for items. When clearing everything and signing in to trakt in the addon i get the following message. 

![image](https://user-images.githubusercontent.com/2564884/147646735-b85d7a1e-82a7-4a32-98bd-058336c16f4c.png)

Don't know if that is related to my issue though. 

I can see calls made to the trakt API in chrome dev tools, But the responses don't seem to contain my watched status for the episodes. 

![image](https://user-images.githubusercontent.com/2564884/147647303-d5f00fde-4f78-4edd-b958-3c5858cef94f.png)

Is there any other tool I should use for development and debugging? As of now I just run "npm start" and then import the build/chrome folder as an unpackaged addon in chrome, and check the chrome devtools console for logs and network calls.

**Comment by schteff** [comment]
I don't personally use Telia Play anymore since HBO Nordic (which was a part of Telia Play) became HBO Max (which is a separate service). 

You can remove all Telia Play code if you want. Or would you appreciate if I did it? :)

**Comment by rafaelgomesxyz** [comment]
Is the old way still working? If it is, it's ok to keep it. If not, go ahead and remove it if you want.

**Comment by schteff** [comment]
No it's completely broken. I made an effort back in august to update it to the new API, but the auth was too complicated and the new API is still missing any "watched timestamp"-information. 

I have made a pull request to remove it.
