### ISSUE TITLE
Sync History

### ISSUE THREAD

**Issue by ITSYV** [trakt-tools/universal-trakt-scrobbler#72]
It would be a good idea to add a message to the sync history page (where you select the streaming services) that you have to be logged in to the service before you can sync.

And maybe a good idea to add a button to the streaming service sync page to go back when an error message is shown.
Also loadHistoryError should maybe be accompanied with why this error could have happened (maybe also a msg that you possibly aren't logged in and a link to the streaming service?)

**Comment by rafaelgomesxyz** [comment]
Yep, I have plans to check for login when loading the history.
