### ISSUE TITLE
Progress always starts at 0

### ISSUE THREAD

**Issue by MrMamen** [trakt-tools/universal-trakt-scrobbler#73]
While this is ultimately up to each streaming service Event-file, there is currently no way to start a scrobble on anything other than 0. The scenario for this is when resuming a playback from the homepage of a streaming service. Calling `updateProgress `before `start`, will usually not work because `TraktItem `is not yet set. One possible solution would be to use `percentageWatched` on `Item`.

**Comment by rafaelgomesxyz** [comment]
I'll be restructuring some things regarding the scrobblers/syncers soon to make adding new services easier, so I'll probably fix this there.
