### ISSUE TITLE
Provide Installation Instructions

### ISSUE THREAD

**Issue by techno-Dev-81** [trakt-tools/universal-trakt-scrobbler#76]
Can details for Installation, setup and configuration be provided, either in the Wiki or a file within the repo?

**Comment by rafaelgomesxyz** [comment]
This extension is still in development. Once it's ready for use, it will be published in the Chrome/Firefox stores.

**Comment by techno-Dev-81** [comment]
@rafaelgomesxyz  Thanks :-)

**Comment by rollecode** [comment]
It's been months. Is there any plugin available yet for Chrome? Can you at least provide some short instructions on how to install dev version of the extension? Thanks!

**Comment by MrMamen** [comment]
@ronilaukkarinen The instructions for creating your own build is found on the Readme-file under development: https://github.com/trakt-tools/universal-trakt-scrobbler#development
nvm in step 5 is not required, but you need to have node/npm installed on your computer: https://nodejs.org/en/download/

**Comment by rollecode** [comment]
It seems to be instructions for development. What I'd like is to just download a dir or crx and install it. Possible?

**Comment by profucius** [comment]
The links to the Chrome and Firefox addon stores on the main github page are confusing, both of them produce a 404 error. A disclaimer should be added above those two images that there is no official release yet, or remove the two images entirely until there is a release.

**Comment by rafaelgomesxyz** [comment]
Closing as duplicate of #61.

You can now download the built zip file for the extension and load it manually from here: https://github.com/trakt-tools/universal-trakt-scrobbler/releases/tag/1.0.0-beta

I'm waiting for the extension to be approved to upload it to the Chrome and Firefox stores.
