### ISSUE TITLE
Crunchyroll and/or Funimation Support

### ISSUE THREAD

**Issue by noah978** [trakt-tools/universal-trakt-scrobbler#79]
I would love to see these other sites added to the list of supported websites for this project. I currently use a script called TraktRoller ([Github](https://github.com/sttz/TraktRoller)), but it doesn't quite work on the newest beta website version of Crunchyroll and I would love to have a unified extension for all of these streaming services that I use.

**Comment by nyffchanium** [comment]
I've implemented history sync for Crunchyroll in PR #165.
No support for scrobbling as for now, but I think I'll look into it sometime.
