### ISSUE TITLE
BBC iPlayer support?

### ISSUE THREAD

**Issue by tomhusband** [trakt-tools/universal-trakt-scrobbler#87]
This project sounds like something a lot of folks would love. I'd like to have BBC iPlayer and Syncler supported.

**Comment by ITSYV** [comment]
Hi Tom

If you're able to code, you can easily add services yourself:
https://github.com/trakt-tools/universal-trakt-scrobbler#how-to-add-more-streaming-services

I just tried making an account with a VPN, but I seem to need a license to watch.
If you're not able to add the service yourself, can you provide a temporary login?

**Comment by tomhusband** [comment]
Thanks but I no longer use Trakt. I didn't find it very useful for the limited amount of shows I watch.
