### ISSUE TITLE
BUG: update new version - regeneratorRuntime not defined

### ISSUE THREAD

**Issue by ITSYV** [trakt-tools/universal-trakt-scrobbler#96]
I just redownloaded the files and did all the commands again and get this error on the updated extension in chrome (brave browser):
Uncaught ReferenceError: regeneratorRuntime is not defined
Context
_generated_background_page.html
Stack-tracering
background.js:2 (anonieme functie)

tried multiple times (deleting, reinstalling, updating...), but can't seem to get it to work anymore.
The plugin itself is active, but when i click on it, it just displays a small white square under the button.
Can't clear caches or anything

"npm install" also gives me errors:
```
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN deprecated uuid@3.0.1: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated intl-messageformat-parser@5.5.1: We've written a new parser that's 6x faster and is backwards compatible. Please use @formatjs/icu-messageformat-parser
npm WARN deprecated webextension-polyfill-ts@0.26.0: This project has moved to @types/webextension-polyfill

```

"npm audit fix":
```
# npm audit report

underscore  1.3.2 - 1.12.0
Severity: high
Arbitrary Code Execution - https://npmjs.com/advisories/1674
fix available via `npm audit fix`
node_modules/underscore
  nomnom  >=1.6.0
  Depends on vulnerable versions of underscore
  node_modules/nomnom

2 high severity vulnerabilities
```

**Comment by MrMamen** [comment]
This is before you can log into trakt or interact with anything? Could you provide a screenshot? You do not get any error in the cli console when running npm start?
EDIT: Also. I advice you to checkout out older commits which worked previously to see if this is a local problem. Either way it would be helpful to see where this bug might have been introduced.

**Comment by ITSYV** [comment]
Yes, it was before i could login with trakt.
Another new pull from git solved the problems.. Don't know what was wrong, but everything seems to work again
